### ISSUE TITLE
Can't use @a or @p for playermod

### ISSUE THREAD

**Issue by gerardvanschip** [CanaryModTeam/CanaryMod#160]
Before Canarymod I used scoreboards to sort of make ranks. I had command blocks that could use the @p to target the player and change their scoreboard. Now I have canarymod I wanted to do the same for playermod but it seems to ignore @p.

Is this a bug or a feature? Seems strange as @p and @a works for most commands.

**Comment by darkdiplomat** [comment]
Most Internal commands require us to add support for @ Target parameters

On a side note: Build numbers aren't really that helpful, once an issue is reported it is reviewed with the most recent builds and when it has be determined fixed, the issue is closed, which may be several builds after the first time its checked.

**Comment by gerardvanschip** [comment]
I only started adding the build thing after I was told off by a dev that I did not include it. Does it not help knowing in which build I had the issue?

**Comment by darkdiplomat** [comment]
I don't know which dev said that but they shall be slapped.
Once a bug is reported, we confirm it with whatever sources we have at hand usually.
Build numbers are alright for knowing when it was first reported but its likely to have been broken earllier and can stay broken for many builds afterwards.

**Comment by darkdiplomat** [comment]
Reopened issue under https://github.com/CanaryModTeam/CanaryLib/issues/71
